force-app/main/default/objects/Donation_Location__c/Donation_Location__c.object-meta.xml
<CustomObject>
    <description>Place where donations are dropped off and collected.</description>
    <label>Donation Location</label>
    <nameField>
        <label>Donation Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donation Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donation_Location__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Active donation location. If active, this location is shown on the web site.</description>
    <inlineHelpText>Active donation location. If active, this location is shown on the web site.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Donation_Location__c/fields/Donation_Location_Details__c.field-meta.xml
<CustomField>
    <fullName>Donation_Location_Details__c</fullName>
    <inlineHelpText>Ex. west side of garage</inlineHelpText>
    <label>Donation Location Details</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Donation_Location__c/fields/Map_URL__c.field-meta.xml
<CustomField>
    <fullName>Map_URL__c</fullName>
    <description>URL to address on Google Maps</description>
    <formula>SUBSTITUTE(&quot;https://maps.google.com/maps?q=&quot; &amp; Street_Address__c &amp; &quot;,+&quot; &amp; City__c &amp; &quot;,+&quot; &amp; TEXT(State__c) &amp; &quot;,+&quot; &amp; Zip_Code__c, &quot; &quot;, &quot;%20&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Map URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donation_Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NY</fullName>
                <default>true</default>
                <label>NY</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donation_Location__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DonationLocationController.cls
public with sharing class DonationLocationController {

    @AuraEnabled
    public static List<Donation_Location__c> getDonationLocations() {
       //System.debug('DonationLocationController - getDonationLocations');
       return [SELECT Id, Name, Map_URL__c, Street_Address__c, City__c, State__c, Zip_Code__c, Donation_Location_Details__c, Website__c FROM Donation_Location__c WHERE Active__c = true];
    }  
    
} // end DonationLocationController