force-app/main/default/objects/Gear_Order_Demographic__c/Gear_Order_Demographic__c.object-meta.xml
<CustomObject>
    <label>Gear Order Demographic</label>
    <nameField>
        <displayFormat>GOD-{0000000000}</displayFormat>
        <label>Demographic Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gear Order Demographics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gear_Order_Demographic__c/fields/Child_Age__c.field-meta.xml
<CustomField>
    <fullName>Child_Age__c</fullName>
    <label>Child Age</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Child_Ages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Demographic__c/fields/Child_Gender__c.field-meta.xml
<CustomField>
    <fullName>Child_Gender__c</fullName>
    <label>Child Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Gender_Demographic</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Demographic__c/fields/Child_Race_Ethnicity__c.field-meta.xml
<CustomField>
    <fullName>Child_Race_Ethnicity__c</fullName>
    <label>Child Race/Ethnicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Race_Ethnicity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Demographic__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>Comments / special requests regarding this child.</description>
    <inlineHelpText>Comments / special requests regarding this child.</inlineHelpText>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/Gear_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Gear Order Item</label>
    <nameField>
        <displayFormat>GOI-{0000000000}</displayFormat>
        <label>Order Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gear Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gear_Order_Item__c/fields/Clothing_Size__c.field-meta.xml
<CustomField>
    <fullName>Clothing_Size__c</fullName>
    <label>Clothing Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Clothing_Sizes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>Comments / special requests regarding this order item.</description>
    <inlineHelpText>Comments / special requests regarding this order item.</inlineHelpText>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Diaper_Size__c.field-meta.xml
<CustomField>
    <fullName>Diaper_Size__c</fullName>
    <label>Diaper Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Diaper_Sizes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Diaper_Swim_Size__c.field-meta.xml
<CustomField>
    <fullName>Diaper_Swim_Size__c</fullName>
    <label>Diaper (Swim) Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Diaper_Swim_Size</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Gear_Order_Demographic__c.field-meta.xml
<CustomField>
    <fullName>Gear_Order_Demographic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gear Order Demographic</label>
    <referenceTo>Gear_Order_Demographic__c</referenceTo>
    <relationshipLabel>Gear Order Items</relationshipLabel>
    <relationshipName>Gear_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Clothing_Seasons</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Child_Ages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unknown</fullName>
        <default>true</default>
        <label>Unknown</label>
    </customValue>
    <customValue>
        <fullName>0-3 months</fullName>
    </customValue>
    <customValue>
        <fullName>3-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6-12 months</fullName>
    </customValue>
    <customValue>
        <fullName>12-18 months</fullName>
    </customValue>
    <customValue>
        <fullName>18-24 months</fullName>
    </customValue>
    <customValue>
        <fullName>2-3 years</fullName>
    </customValue>
    <customValue>
        <fullName>3-4 years</fullName>
    </customValue>
    <customValue>
        <fullName>4-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>5-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>10+ years</fullName>
    </customValue>
    <masterLabel>Child Ages</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Clothing_Seasons.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Summer</fullName>
    </customValue>
    <customValue>
        <fullName>Winter</fullName>
    </customValue>
    <masterLabel>Clothing Seasons</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Clothing_Sizes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>N/A</fullName>
        <default>true</default>
        <label>N/A</label>
    </customValue>
    <customValue>
        <fullName>0-3 months</fullName>
    </customValue>
    <customValue>
        <fullName>3-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6-12 months</fullName>
    </customValue>
    <customValue>
        <fullName>12-18 months</fullName>
    </customValue>
    <customValue>
        <fullName>18-24 months</fullName>
    </customValue>
    <customValue>
        <fullName>2T</fullName>
    </customValue>
    <customValue>
        <fullName>3T</fullName>
    </customValue>
    <masterLabel>Clothing Sizes</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Diaper_Sizes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Newborn (Up to 8 lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 1 (8-14lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 2 (12-18lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 3 (16-28lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 4 (22-37bs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 5 (27+lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 6 (35+lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Pull Ups (2T-3T)</fullName>
    </customValue>
    <customValue>
        <fullName>Pull Ups (3T-4T)</fullName>
    </customValue>
    <customValue>
        <fullName>Pull Ups (4T-5T)</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Diapers (Small 16-26lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Diapers (Medium 24-34 lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Diapers (Large 32+ lbs)</fullName>
    </customValue>
    <masterLabel>Diaper Sizes</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Diaper_Swim_Size.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Small 16-26#</fullName>
    </customValue>
    <customValue>
        <fullName>Medium 24-34#</fullName>
    </customValue>
    <customValue>
        <fullName>Large 32 lbs +</fullName>
    </customValue>
    <customValue>
        <fullName>pull-ups 2T-3T</fullName>
        <isActive>false</isActive>
        <label>pull-ups 2T-3T</label>
    </customValue>
    <customValue>
        <fullName>pull-ups 3T-4T</fullName>
        <isActive>false</isActive>
        <label>pull-ups 3T-4T</label>
    </customValue>
    <customValue>
        <fullName>pull-ups 4T-5T</fullName>
        <isActive>false</isActive>
        <label>pull-ups 4T-5T</label>
    </customValue>
    <masterLabel>Diaper (Swim) Size</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Gender_Demographic.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unknown</fullName>
        <default>true</default>
        <label>Unknown</label>
    </customValue>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <masterLabel>Gender Demographic</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Race_Ethnicity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Caucasian</fullName>
    </customValue>
    <customValue>
        <fullName>Native American</fullName>
    </customValue>
    <customValue>
        <fullName>African American</fullName>
    </customValue>
    <customValue>
        <fullName>Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Asian</fullName>
    </customValue>
    <customValue>
        <fullName>African</fullName>
    </customValue>
    <customValue>
        <fullName>Other/Unknown</fullName>
        <default>true</default>
        <label>Other/Unknown</label>
    </customValue>
    <masterLabel>Race/Ethnicity</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductSummary.cls
global class ProductSummary {

	public String productCategory {get;set;}        
	public String productName {get;set;}        
	public Decimal quantity {get;set;}        
	public List<OrderItemDetail> orderItemDetails {get;set;}
    
    global class OrderItemDetail {
        public Gear_Order_Demographic__c demographic { 
            get {
            	if (demographic == null) demographic = new Gear_Order_Demographic__c();
                return demographic;
        	} 
        	set;
        }
        
        public Gear_Order_Item__c orderItem {
            get {
            	if (orderItem == null) orderItem = new Gear_Order_Item__c();
                return orderItem;
        	} 
        	set;
        }
        
        public String demographicDisplay { 
            get {                
				String child = (demographic.Child_Gender__c == null) ? 'UNKNOWN' : demographic.Child_Gender__c;
                String gender = (demographic.Child_Age__c == null) ? 'UNKNOWN' : demographic.Child_Age__c;
                String ethnicity = (demographic.Child_Race_Ethnicity__c == null) ? 'UNKNOWN' : demographic.Child_Race_Ethnicity__c;
                return child + ' | ' + gender + ' | ' + ethnicity;                    
        	}
   		}
        
        public String orderItemDisplay { 
            get {
            	String value = '';
                if (orderItem.Season__c != null) value += 'Season: ' + orderItem.Season__c + '<br/>';
                if (orderItem.Clothing_Size__c != null) value += 'Clothing Size: ' + orderItem.Clothing_Size__c + '<br/>';
                if (orderItem.Diaper_Size__c != null) value += 'Diaper Size: ' + orderItem.Diaper_Size__c + '<br/>';
                if (orderItem.Diaper_Swim_Size__c != null) value += 'Diaper (Swim) Size: ' + orderItem.Diaper_Swim_Size__c + '<br/>';
                return value; 
        	}
   		}
    
        public String commentsDisplay { 
            get {
            	String value = '';
                if (demographic.Comment__c != null) value += demographic.Comment__c + '<br/>';
                if (orderItem.Comment__c != null) value += orderItem.Comment__c + '<br/>';
                return value;
        	}
   		}
        
    } // end OrderItemDetail
    
} // end ProductSummary