force-app/main/default/objects/Account/fields/Executive_Director__c.field-meta.xml
<CustomField>
    <fullName>Executive_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive Director</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Partner Orgs (Executive Director)</relationshipLabel>
    <relationshipName>Partner_Orgs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Latest_Liability_Waiver__c.field-meta.xml
<CustomField>
    <fullName>Latest_Liability_Waiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Liability Waiver</label>
    <referenceTo>Partner_Agreement__c</referenceTo>
    <relationshipLabel>Accounts (Latest Liability Waiver)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Latest_Partner_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Latest_Partner_Agreement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Latest Partner Agreement</label>
    <referenceTo>Partner_Agreement__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Agreement__c/Partner_Agreement__c.object-meta.xml
<CustomObject>
    <label>Partner Agreement</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Agreement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Agreement__c/fields/Executive_Director__c.field-meta.xml
<CustomField>
    <fullName>Executive_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WeeCycle Executive Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Partner_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PartnerAgreements_Approved.cls
global without sharing class PartnerAgreements_Approved {

    @InvocableMethod(label='Partner Agreements Approved')
    global static List<ID> partnerAgreementsApproved(List<ID> partnerIDs) {

        List<ID> approverIDs = new List<ID>();

        if (partnerIDs != null) {
            System.debug('PartnerAgreements_Approved > partnerIDs: ' + partnerIDs.size());

            for (ID partnerID : partnerIDs) {

                System.debug('PartnerAgreements_Approved > partnerID: ' + partnerID);

                // get partner account
                Account partner = [SELECT Id, Name,
                        Latest_Partner_Agreement__c, Latest_Liability_Waiver__c,
                        Executive_Director__c, Executive_Director__r.Email
                        FROM Account WHERE Id = :partnerID LIMIT 1
                ];

                // agreements
                List<ID> partnerAgreementIDs = new List<ID>();
                partnerAgreementIDs.add(partner.Latest_Partner_Agreement__c);
                partnerAgreementIDs.add(partner.Latest_Liability_Waiver__c);

                // sign partner agreements
                List<Partner_Agreement__c> paList = PartnerSignupController.signPartnerAgreements(partnerAgreementIDs);
                System.debug('PartnerAgreements_Approved > partner agreements signed: ' + paList);

                // check all agreements were signed ok
                if (partnerAgreementIDs.size() == paList.size()) {

                    // get approver of the partner agreements
                    Partner_Agreement__c pa = paList.get(0);
                    ID approverID = pa.Executive_Director__c;
                    approverIDs.add(approverID);
                }

            } // end for
        }

        return approverIDs;
        
    } // end partnerAgreementsApproved
    
} // end PartnerAgreements_Approved