force-app/main/default/objects/Account/fields/Families_Receiving_Support__c.field-meta.xml
<CustomField>
    <fullName>Families_Receiving_Support__c</fullName>
    <inlineHelpText>Estimated number of children receiving support from WeeCycle through this organization in current calendar year.</inlineHelpText>
    <label>Children Receiving Support</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demographic_Served__c/Demographic_Served__c.object-meta.xml
<CustomObject>
    <label>Demographic Served</label>
    <nameField>
        <displayFormat>DS-{00000}</displayFormat>
        <label>Demographic Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demographics Served</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demographic_Served__c/fields/Partner_Organization__c.field-meta.xml
<CustomField>
    <fullName>Partner_Organization__c</fullName>
    <label>Partner Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Demographics Served</relationshipLabel>
    <relationshipName>Demographics_Served</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Demographic_Served__c/fields/Percent_Served__c.field-meta.xml
<CustomField>
    <fullName>Percent_Served__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Percent Served</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Demographic_Served__c/fields/Race_Ethnicity__c.field-meta.xml
<CustomField>
    <fullName>Race_Ethnicity__c</fullName>
    <label>Race Ethnicity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Race_Ethnicity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order__c/Gear_Order__c.object-meta.xml
<CustomObject>
    <description>Orders for baby gear</description>
    <label>Gear Order</label>
    <nameField>
        <displayFormat>GO-{000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gear Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gear_Order__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>Comments / special requests regarding this order.</description>
    <inlineHelpText>Comments / special requests regarding this order.</inlineHelpText>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gear_Order__c/fields/Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Line_Items__c</fullName>
    <label>Line Items</label>
    <summaryForeignKey>Gear_Order_Item__c.Gear_Order__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Gear_Order__c/fields/NoTimesWork__c.field-meta.xml
<CustomField>
    <fullName>NoTimesWork__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The partner has indicated no preferred pick times.</description>
    <inlineHelpText>The partner has indicated no preferred pick times.</inlineHelpText>
    <label>No Times Work</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Gear_Order__c/fields/NoTimesWork_Comment__c.field-meta.xml
<CustomField>
    <fullName>NoTimesWork_Comment__c</fullName>
    <label>No Times Work Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Gear_Order__c/fields/Num_Children_Served__c.field-meta.xml
<CustomField>
    <fullName>Num_Children_Served__c</fullName>
    <description>The number of children served with this gear order. This number is calculated as the number of demographics entered for this order.</description>
    <inlineHelpText>The number of children served with this gear order. This number is calculated as the number of demographics entered for this order.</inlineHelpText>
    <label># Children Served</label>
    <summaryForeignKey>Gear_Order_Demographic__c.Gear_Order__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Gear_Order__c/fields/Num_Families_Served__c.field-meta.xml
<CustomField>
    <fullName>Num_Families_Served__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of families served with this gear order. This number is entered by the partner when submitting the order.</description>
    <inlineHelpText>The number of families served with this gear order. This number is entered by the partner when submitting the order.</inlineHelpText>
    <label># Families Served</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gear_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Unfulfilled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order__c/fields/Partner_Organization__c.field-meta.xml
<CustomField>
    <fullName>Partner_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Gear Orders</relationshipLabel>
    <relationshipName>Gear_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gear_Order__c/fields/Pickup_Choice_1__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Choice_1__c</fullName>
    <label>Preferred Pickup Time 1</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Gear_Order__c/fields/Pickup_Choice_2__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Choice_2__c</fullName>
    <label>Preferred Pickup Time 2</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Demographic__c/Gear_Order_Demographic__c.object-meta.xml
<CustomObject>
    <label>Gear Order Demographic</label>
    <nameField>
        <displayFormat>GOD-{0000000000}</displayFormat>
        <label>Demographic Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gear Order Demographics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gear_Order_Demographic__c/fields/Child_Age__c.field-meta.xml
<CustomField>
    <fullName>Child_Age__c</fullName>
    <label>Child Age</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Child_Ages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Demographic__c/fields/Child_Alias__c.field-meta.xml
<CustomField>
    <fullName>Child_Alias__c</fullName>
    <defaultValue>&#39;NO ALIAS&#39;</defaultValue>
    <description>Alias or nickname of this child (could be the child&#39;s name, address, etc) so the partner can map the child demographic info to the order items for that child.</description>
    <inlineHelpText>Alias or nickname of this child (could be the child&#39;s name, address, etc) so the partner can map the child demographic info to the order items for that child.</inlineHelpText>
    <label>Child Alias / Nickname</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Demographic__c/fields/Child_Gender__c.field-meta.xml
<CustomField>
    <fullName>Child_Gender__c</fullName>
    <label>Child Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Gender_Demographic</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Demographic__c/fields/Child_Race_Ethnicity__c.field-meta.xml
<CustomField>
    <fullName>Child_Race_Ethnicity__c</fullName>
    <label>Child Race/Ethnicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Race_Ethnicity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Demographic__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>Comments / special requests regarding this child.</description>
    <inlineHelpText>Comments / special requests regarding this child.</inlineHelpText>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Demographic__c/fields/Gear_Order__c.field-meta.xml
<CustomField>
    <fullName>Gear_Order__c</fullName>
    <label>Gear Order</label>
    <referenceTo>Gear_Order__c</referenceTo>
    <relationshipLabel>Gear Order Demographics</relationshipLabel>
    <relationshipName>Gear_Order_Demographics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/Gear_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Gear Order Item</label>
    <nameField>
        <displayFormat>GOI-{0000000000}</displayFormat>
        <label>Order Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gear Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gear_Order_Item__c/fields/Clothing_Size__c.field-meta.xml
<CustomField>
    <fullName>Clothing_Size__c</fullName>
    <label>Clothing Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Clothing_Sizes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>Comments / special requests regarding this order item.</description>
    <inlineHelpText>Comments / special requests regarding this order item.</inlineHelpText>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Diaper_Size__c.field-meta.xml
<CustomField>
    <fullName>Diaper_Size__c</fullName>
    <label>Diaper Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Diaper_Sizes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Diaper_Swim_Size__c.field-meta.xml
<CustomField>
    <fullName>Diaper_Swim_Size__c</fullName>
    <label>Diaper (Swim) Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Diaper_Swim_Size</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Gear_Order__c.field-meta.xml
<CustomField>
    <fullName>Gear_Order__c</fullName>
    <label>Gear Order</label>
    <referenceTo>Gear_Order__c</referenceTo>
    <relationshipLabel>Gear Order Items</relationshipLabel>
    <relationshipName>Gear_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Gear_Order_Demographic__c.field-meta.xml
<CustomField>
    <fullName>Gear_Order_Demographic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gear Order Demographic</label>
    <referenceTo>Gear_Order_Demographic__c</referenceTo>
    <relationshipLabel>Gear Order Items</relationshipLabel>
    <relationshipName>Gear_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Gear Order Items</relationshipLabel>
    <relationshipName>Gear_Order_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The number of item bundles of this product.</description>
    <inlineHelpText>The number of item bundles of this product.</inlineHelpText>
    <label>Quantity (Bundles)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Clothing_Seasons</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Custom Product object for donation items</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <description>same as Product Family on standard Product</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donation_Item_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of items of this product in inventory now. This field is calculated.</description>
    <inlineHelpText>The number of items of this product in inventory now. This field is calculated.</inlineHelpText>
    <label># In Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Child_Ages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unknown</fullName>
        <default>true</default>
        <label>Unknown</label>
    </customValue>
    <customValue>
        <fullName>0-3 months</fullName>
    </customValue>
    <customValue>
        <fullName>3-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6-12 months</fullName>
    </customValue>
    <customValue>
        <fullName>12-18 months</fullName>
    </customValue>
    <customValue>
        <fullName>18-24 months</fullName>
    </customValue>
    <customValue>
        <fullName>2-3 years</fullName>
    </customValue>
    <customValue>
        <fullName>3-4 years</fullName>
    </customValue>
    <customValue>
        <fullName>4-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>5-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>10+ years</fullName>
    </customValue>
    <masterLabel>Child Ages</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Clothing_Seasons.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Summer</fullName>
    </customValue>
    <customValue>
        <fullName>Winter</fullName>
    </customValue>
    <masterLabel>Clothing Seasons</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Clothing_Sizes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>N/A</fullName>
        <default>true</default>
        <label>N/A</label>
    </customValue>
    <customValue>
        <fullName>0-3 months</fullName>
    </customValue>
    <customValue>
        <fullName>3-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6-12 months</fullName>
    </customValue>
    <customValue>
        <fullName>12-18 months</fullName>
    </customValue>
    <customValue>
        <fullName>18-24 months</fullName>
    </customValue>
    <customValue>
        <fullName>2T</fullName>
    </customValue>
    <customValue>
        <fullName>3T</fullName>
    </customValue>
    <masterLabel>Clothing Sizes</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Diaper_Sizes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Newborn (Up to 8 lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 1 (8-14lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 2 (12-18lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 3 (16-28lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 4 (22-37bs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 5 (27+lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 6 (35+lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Pull Ups (2T-3T)</fullName>
    </customValue>
    <customValue>
        <fullName>Pull Ups (3T-4T)</fullName>
    </customValue>
    <customValue>
        <fullName>Pull Ups (4T-5T)</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Diapers (Small 16-26lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Diapers (Medium 24-34 lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Diapers (Large 32+ lbs)</fullName>
    </customValue>
    <masterLabel>Diaper Sizes</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Diaper_Swim_Size.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Small 16-26#</fullName>
    </customValue>
    <customValue>
        <fullName>Medium 24-34#</fullName>
    </customValue>
    <customValue>
        <fullName>Large 32 lbs +</fullName>
    </customValue>
    <customValue>
        <fullName>pull-ups 2T-3T</fullName>
        <isActive>false</isActive>
        <label>pull-ups 2T-3T</label>
    </customValue>
    <customValue>
        <fullName>pull-ups 3T-4T</fullName>
        <isActive>false</isActive>
        <label>pull-ups 3T-4T</label>
    </customValue>
    <customValue>
        <fullName>pull-ups 4T-5T</fullName>
        <isActive>false</isActive>
        <label>pull-ups 4T-5T</label>
    </customValue>
    <masterLabel>Diaper (Swim) Size</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Donation_Item_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Gear</fullName>
    </customValue>
    <customValue>
        <fullName>Activity</fullName>
    </customValue>
    <customValue>
        <fullName>Feeding</fullName>
    </customValue>
    <customValue>
        <fullName>Nursery</fullName>
    </customValue>
    <customValue>
        <fullName>Health &amp; Safety</fullName>
    </customValue>
    <customValue>
        <fullName>Toys</fullName>
    </customValue>
    <customValue>
        <fullName>Books</fullName>
    </customValue>
    <customValue>
        <fullName>Videos &amp; Music</fullName>
    </customValue>
    <customValue>
        <fullName>Clothing</fullName>
    </customValue>
    <customValue>
        <fullName>Bath &amp; Potty</fullName>
    </customValue>
    <description>Donation Item Category</description>
    <masterLabel>Donation Item Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Gender_Demographic.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unknown</fullName>
        <default>true</default>
        <label>Unknown</label>
    </customValue>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <masterLabel>Gender Demographic</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Race_Ethnicity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Caucasian</fullName>
    </customValue>
    <customValue>
        <fullName>Native American</fullName>
    </customValue>
    <customValue>
        <fullName>African American</fullName>
    </customValue>
    <customValue>
        <fullName>Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Asian</fullName>
    </customValue>
    <customValue>
        <fullName>African</fullName>
    </customValue>
    <customValue>
        <fullName>Other/Unknown</fullName>
        <default>true</default>
        <label>Other/Unknown</label>
    </customValue>
    <masterLabel>Race/Ethnicity</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GearOrderController.cls
public without sharing class GearOrderController {

    // ******** controller for lightning components: GearOrder_ItemEdit, GearOrder_PickupTime, GearOrder_EnterBulkDemographics

    // ******** OPERATIONS FOR lightning component: GearOrder_ItemEdit
    
    @AuraEnabled
    public static List<Account> getPartnerOrgSelection() {
       System.debug('GearOrderController > getPartnerOrgSelection');
       return [SELECT Id, Name FROM Account WHERE Type='Partner_Current' ORDER BY Name ASC];
    } // end getPartnerOrgSelection
    
    @AuraEnabled
    public static List<Gear_Order__c> getGearOrder(String orderID, String orderName) {
       	System.debug('GearOrderController > getGearOrder - orderID: ' + orderID + ', orderName: ' + orderName);
       	if (orderID != null) {
       		return [SELECT Id, Name, Order_Status__c, Comment__c, Num_Children_Served__c, Line_Items__c FROM Gear_Order__c WHERE Id=:orderID];
        } else {
            return [SELECT Id, Name, Order_Status__c, Comment__c, Num_Children_Served__c, Line_Items__c FROM Gear_Order__c WHERE Name=:orderName];
        }
    } // end getGearOrder

    @AuraEnabled
    public static List<Gear_Order_Demographic__c> getGearOrderDemographicSelection(String orderID) {
       	System.debug('GearOrderController > getGearOrderDemographicSelection - orderID: ' + orderID);
        
        List<Gear_Order_Demographic__c> demographicsList =
            [SELECT Id, Name, Child_Alias__c, Child_Age__c, Child_Gender__c, Child_Race_Ethnicity__c FROM Gear_Order_Demographic__c WHERE Gear_Order__c = :orderID];        

        return demographicsList;
        
    } // end getGearOrderDemographicSelection
    
    @AuraEnabled
    public static List<Gear_Order_Item__c> getGearOrderItems(String orderID) {
       	System.debug('GearOrderController > getGearOrderItems - orderID: ' + orderID);
        
        List<Gear_Order_Item__c> orderItemList = null;
       	
        List<Gear_Order__c> orderList = getGearOrder(orderID, null);
        if (orderList.size() > 0) {
            Gear_Order__c order = orderList.get(0);          
            orderItemList = [SELECT Id, Name, Gear_Order_Demographic__c, Product__r.Id, Product__r.Name, Product__r.Family__c, Quantity__c, Season__c, Clothing_Size__c, Diaper_Size__c, Diaper_Swim_Size__c, Comment__c FROM Gear_Order_Item__c WHERE Gear_Order__c = :order.Id];        
        }
        
        if (orderItemList == null) {
            orderItemList = new List<Gear_Order_Item__c>();
        }
        
        return orderItemList;
        
    } // end getGearOrderItems    
    
    @AuraEnabled
    public static List<Product__c> getProductSelection() {
        System.debug('GearOrderController > getProductSelection');
        return ProductController.getProducts();

    } // end getProductSelection
    
    @AuraEnabled
    public static Gear_Order_Item__c createGearOrderItem(String orderID, String demographicID, 
                                                         String productID, Integer quantity, 
                                         				 String season, String clothingSize, String diaperSize,
                                                         String comment) {
        System.debug('GearOrderController > createGearOrderItem - orderID: ' + orderID  + ', demographicID:' + demographicID
        	+ ', productID: ' + productID + ', quantity: ' + quantity
        	+ ', season: ' + season + ', clothingSize: ' + clothingSize + ', diaperSize: ' + diaperSize
            + ', comment: ' + comment);
        
        // orderItem
        Gear_Order_Item__c orderItem = new Gear_Order_Item__c();
        orderItem.Gear_Order__c = orderID;
        orderItem.Gear_Order_Demographic__c = demographicID;
        orderItem.Product__c = productID;
        orderItem.Quantity__c = Integer.valueOf(quantity);
        orderItem.Season__c = season;
        orderItem.Clothing_Size__c = clothingSize;
        orderItem.Diaper_Size__c = diaperSize;
        orderItem.Comment__c = comment;                                                     
            
        insert orderItem;
        System.debug('GearOrderController > createGearOrderItem - item created: ' + orderItem);
		return orderItem;
        
    } // end createGearOrderItem
    
    @AuraEnabled 
    public static Gear_Order_Item__c updateGearOrderItem(String orderID, String orderItemID, 
                                                         String productID, Integer quantity, 
                                         				 String season, String clothingSize, String diaperSize,
                                                         String comment) {
        System.debug('GearOrderController > updateGearOrderItem - orderID: ' + orderID + ', orderItemID: ' + orderItemID
        	+ ', productID: ' + productID + ', quantity: ' + quantity
        	+ ', season: ' + season + ', clothingSize: ' + clothingSize + ', diaperSize: ' + diaperSize
            + ', comment: ' + comment);
        
        // orderItem
        Gear_Order_Item__c orderItem = new Gear_Order_Item__c();
        orderItem.Gear_Order__c = orderID;
        orderItem.Id = orderItemID;
            
        // update 
        orderItem.Product__c = productID;
        orderItem.Quantity__c = Integer.valueOf(quantity);
        orderItem.Season__c = season;
        orderItem.Clothing_Size__c = clothingSize;
        orderItem.Diaper_Size__c = diaperSize; 
        orderItem.Comment__c = comment;                                                     
            
        update orderItem;
        System.debug('GearOrderController > updateGearOrderItem - item updated: ' + orderItem);
        return orderItem;
        
    } // end updateGearOrderItem      
    
    @AuraEnabled
    public static Gear_Order_Item__c deleteGearOrderItem(String orderID, String orderItemID) {
        System.debug('GearOrderController > deleteGearOrderItem - orderID: ' + orderID + ', orderItemID: ' + orderItemID);
        
        Gear_Order_Item__c orderItem = new Gear_Order_Item__c();
        orderItem.Gear_Order__c = orderID;
        orderItem.Id = orderItemID;
        
        delete orderItem;
        System.debug('GearOrderController > deleteGearOrderItem - item deleted: ' + orderItem);
        return orderItem;
        
    } // end updateGearOrderItem   
    
    // Option - inner class 
    public class Option {
        @AuraEnabled
        String label {get;set;}
        @AuraEnabled
        String value {get;set;}
        @AuraEnabled
        Boolean defaultValue {get;set;}
    }
    
    // getPicklistValues - returns a list of inner class Option
    @AuraEnabled
    public static List<Option> getPicklistValues(SObject obj, String field) {
        System.debug('GearOrderController > getPicklistValues - obj: ' + obj + ', field: ' + field);
        List<Option> options = new List<Option>();
        
        // Get the object type of the SObject.
        Schema.sObjectType objType = obj.getSObjectType();
        
        // Describe the SObject using its object type.
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        
        // Get a map of fields for the SObject
        Map< String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
        
        // Get the list of picklist values for this field.
        List<Schema.PicklistEntry> pickListOptions = fieldMap.get(field).getDescribe().getPickListValues();
        
        // Add these values to the select option list
        for (Schema.PicklistEntry a: pickListOptions) {
            Option option = new Option();
            option.label = a.getLabel();
            option.value = a.getValue();
            if (a.isDefaultValue()) {
                option.defaultValue = true;
            }            
            options.add(option);
        }
        
        System.debug('GearOrderController > getPicklistValues - values: ' + options);
        //options.sort();
        return options;
    } // getPicklistValues
    
    @AuraEnabled 
    public static String updateOrderComment(String orderID, String comment) {
        System.debug('GearOrderController > updateOrderComment - orderID: ' + orderID + ', comment: ' + comment);
        
        // order
        Gear_Order__c order = new Gear_Order__c();
        order.Id = orderID;
            
        // update 
        order.Comment__c =  comment;
            
        update order;
        System.debug('GearOrderController > updateOrderComment - order updated: ' + order);
        return 'ORDER_UPDATED';
        
    } // end updateOrderComment    
    
    // ******** OPERATIONS FOR lightning component: GearOrder_PickupTime

    @AuraEnabled
    public static List<String> getNextPickupDatesAvailable(Integer numDates) {
        // dateString format '04/14/2019'
        // returns a list of dates, the next dates available for order pickup.
        // numDates - indicates the number of future available dates to return.
        // availability is determined by querying 'all day' calendar events that have the subject 'ORDER PICKUPS'
        // that start today or in the future.

        System.debug('GearOrderController > getNextPickupDatesAvailable - numDates: ' + numDates);

        String availableEventName = 'ORDER PICKUPS';

        // example query:
        // SELECT Owner.Name, StartDateTime from Event WHERE IsAllDayEvent=true AND Subject='ORDER PICKUPS' AND StartDateTime >= TODAY ORDER BY StartDateTime LIMIT 3
        String query = 'SELECT StartDateTime FROM Event';

        // where clause
        String whereClause = 'WHERE Subject=\'' + availableEventName + '\' AND IsAllDayEvent=true AND ActivityDate >= TODAY';
        query += ' ' + whereClause + ' ORDER BY ActivityDate LIMIT ' + numDates;
        System.debug('GearOrderController > getNextPickupDatesAvailable - query: ' + query);

        List<String> nextDates = new List<String>();

        List<Event> availableEvents = Database.query(query);
        if ((availableEvents != null) && (availableEvents.size() > 0)) {
            System.debug('GearOrderController > getNextPickupDatesAvailable - availableEvents: ' + availableEvents);

            for (Integer i = 0; i < availableEvents.size(); ++i) {
                DateTime eventDate = availableEvents[i].StartDateTime;
                String eventDateString = eventDate.format('MM/dd/yyyy', 'GMT');
                //System.debug('GearOrderController > getNextPickupDatesAvailable - eventDate: ' + eventDate);
                nextDates.add(eventDateString);
            }
        }

        System.debug('GearOrderController > getNextPickupDatesAvailable - nextDates: ' + nextDates);
        return nextDates;

    } // end getNextPickupDatesAvailable
    
    @AuraEnabled 
    public static String updatePreferredPickupTimes(String orderID, Boolean noTimesWork, String noTimesWorkComment, String pickupTimezone, String pickupDateTime1String, String pickupDateTime2String) {
    	// dateTimeString format '11/10/2018 10:00 am'
    	// 
        System.debug('GearOrderDemographicsController > updatePreferredPickupTimes - orderID: ' + orderID + ', noTimesWork: ' + noTimesWork + ', noTimesWorkComment: ' + noTimesWorkComment + ', pickupTimezone: ' + pickupTimezone + ', pickupDateTime1String: ' + pickupDateTime1String + ', pickupDateTime2String: ' + pickupDateTime2String);

        // order
        Gear_Order__c order = new Gear_Order__c();
        order.Id = orderID;
        
        // update noTimesWork
        if (noTimesWork) {
            order.NoTimesWork__c = true;
            order.NoTimesWork_Comment__c = noTimesWorkComment;
            
            // unset pickup choices
            order.Pickup_Choice_1__c =  null;
        	order.Pickup_Choice_2__c =  null;
        }
            
        // update pickup choices        
        if ((pickupDateTime1String != null) && (pickupDateTime2String != null)) {
            
            // parse into dates (string format: 10/14/2011 11:46 AM) and adjust to pickupTimezone
            DateTime pickupDateTime1 = getTimezoneAdjustedDate(pickupTimezone, pickupDateTime1String);
            DateTime pickupDateTime2 = getTimezoneAdjustedDate(pickupTimezone, pickupDateTime2String);
            System.debug('GearOrderDemographicsController > updatePreferredPickupTimes - pickupDateTime1: ' + pickupDateTime1 + ', pickupDateTime2: ' + pickupDateTime2);
        	order.Pickup_Choice_1__c =  pickupDateTime1;
        	order.Pickup_Choice_2__c =  pickupDateTime2;
            
            // unset NoTimesWork
            order.NoTimesWork__c = false;
            order.NoTimesWork_Comment__c = null;
        }
            
        update order;
        System.debug('GearOrderDemographicsController > updatePreferredPickupTimes - order updated: ' + order);
        return 'ORDER_UPDATED - user timezone: ' + UserInfo.getTimeZone().getID();
        
    } // end updateOrderComment 
    
    public static DateTime getTimezoneAdjustedDate(String targetTimezone, String dateTimeString) {
        // dateTimeString format '11/10/2018 10:00 am'
            
		System.debug('GearOrderController > getTimezoneAdjustedDate - targetTimezone: ' + targetTimezone  + ', dateTimeString: ' + dateTimeString);
        
        // parse into dates (string format: 11/10/2018 10:00 am) and adjust to pickupTimezone
        // for now assuming the date created from DateTime.parse is in GMT time 
        // because this is called from an unauthenticated user       
        
        // what the time looks like coming in
        DateTime theDateTime = parseDateTimeStringGMT(dateTimeString);
        //DateTime theDateTime = DateTime.parse(dateTimeString);
        System.debug('GearOrderController > getTimezoneAdjustedDate - theDateTime (GMT): ' + theDateTime);
    
        // adjust the stored UTC time based on the offset of the given timezone (this automatically adjusts for daylight savings time)
        TimeZone target_tz = Timezone.getTimeZone(targetTimezone);
        Long timezoneOffset = target_tz.getOffset(theDateTime);
        Long minDiff = timezoneOffset / 1000 / 60;
        Long hourDiff = minDiff / 60;
        System.debug('GearOrderController > getTimezoneAdjustedDate - target timezone: ' + target_tz.getDisplayName() + ', id: ' + target_tz.getID() + ', offset: ' + timezoneOffset + ' (' + hourDiff +' hours)');
        DateTime adjustedDateTime = theDateTime.addMinutes(minDiff.intValue() * -1);
        String theDateTime_gmt = adjustedDateTime.format('yyyy-MM-dd HH:mm:ss', 'GMT');
        String theDateTime_targetTimezone = adjustedDateTime.format('yyyy-MM-dd HH:mm:ss', targetTimezone);            
        System.debug('GearOrderController > getTimezoneAdjustedDate - theDateTime (adjusted) gmt: ' + theDateTime_gmt + ', targetTimezone: ' + targetTimezone  + ', theDateTime_targetTimezone: ' + theDateTime_targetTimezone);
        
        return adjustedDateTime; 
        
    } // end getTimezoneAdjustedDate
    
    public static DateTime parseDateTimeStringGMT(String dateTimeString) {
        // parse dateTimeString format '11/10/2018 10:00 am'
        // and create DateTime in GMT
        DateTime theDate = null;
        
        List<String> toks = dateTimeString.split(' ');
        //System.debug('toks: ' + toks + ', size: ' + toks.size());
        
        // date
        List<String> dateToks = toks[0].split('/');
        //System.debug('dateToks: ' + dateToks);
        Integer month = Integer.valueof(dateToks[0]);
        Integer day = Integer.valueof(dateToks[1]);
        Integer year = Integer.valueof(dateToks[2]);
        //System.debug('year: ' + year + ', month: ' + month + ', day: ' + day);
        
        // time
        if (toks.size() == 3) {
            List<String> timeToks = toks[1].split(':');
            Integer hour = Integer.valueof(timeToks[0]);
            Integer minute = Integer.valueof(timeToks[1]);
            String am_pm = toks[2];
            //System.debug('hour: ' + hour + ', minute: ' + minute + ', am_pm: ' + am_pm);
            
            if ((am_pm == 'pm') && (hour != 12)) {
                hour += 12;
            } else if ((am_pm == 'am') && (hour == 12)) {
                hour = 0;
            }
            
            //System.debug('year: ' + year + ', month: ' + month + ', day: ' + day + ', hour: ' + hour + ', minute: ' + minute );
            theDate = DateTime.newInstanceGmt(year, month, day, hour, minute, 0);
        } else {
            theDate = DateTime.newInstanceGmt(year, month, day);
        }
        
        System.debug('GearOrderController > parseDateTimeStringGMT - theDate: ' + theDate);
        return theDate;
        
    } // end parseDateTimeStringGMT
    
    // ******** OPERATIONS FOR lightning component: GearOrder_EnterBulkDemographics 

    @AuraEnabled
    public static List<Gear_Order__c> getGearOrderForBulkDemographics(String orderID, String orderName) {
       	System.debug('GearOrderController > getGearOrderForBulkDemographics - orderID: ' + orderID + ', orderName: ' + orderName);
       	if (orderID != null) {
       		return [SELECT Id, Name, Partner_Organization__c, Num_Families_Served__c FROM Gear_Order__c WHERE Id=:orderID];
        } else {
            return [SELECT Id, Name, Partner_Organization__c, Num_Families_Served__c FROM Gear_Order__c WHERE Name=:orderName];
        }
    } // end getGearOrder

    @AuraEnabled
    public static DemographicsServedDetails getDemographicsServed(String accountID) {
        System.debug('GearOrderController > getDemographicsServed - accountID: ' + accountID);
        DemographicsServedDetails details;
        if (accountID != null) {
            details = new DemographicsServedDetails();

            // numFamiliesServed
            Account account = [SELECT Families_Receiving_Support__c FROM Account WHERE ID = :accountID LIMIT 1];
            System.debug('GearOrderController > getDemographicsServed - account: ' + account);
            Decimal numFamilesServed = account.Families_Receiving_Support__c;
            if (numFamilesServed == null) numFamilesServed = 0;
            details.numFamiliesServed = Integer.valueOf(numFamilesServed);

            // demographicServedList
            Gear_Order_Demographic__c obj = new Gear_Order_Demographic__c();
            String field = 'Child_Race_Ethnicity__c';
            List<Option> options = getPicklistValues(obj, field);

            // map of race/ethnicity : Demographic_Served__c
            List<Demographic_Served__c> demographicServedList = [SELECT Id, Race_Ethnicity__c, Percent_Served__c FROM Demographic_Served__c WHERE Partner_Organization__c=:accountID];
            Map<String, Demographic_Served__c> demographicMap = new Map<String, Demographic_Served__c>();
            for (Demographic_Served__c d : demographicServedList) {
                demographicMap.put(d.Race_Ethnicity__c, d);
            }

            // add any picklist race_ethnicity values that aren't in the existing account demographics served
            // so that they'll display in the table for editing
            for (Option o : options) {
                if (!demographicMap.containsKey(o.label)) {
                    Demographic_Served__c d = new Demographic_Served__c(Race_Ethnicity__c = o.label, Percent_Served__c = 0);
                    demographicServedList.add(d);
                }
            }
            details.demographicServedList = demographicServedList;
        }
        return details;
    } // end getDemographicsServed

    // DemographicsServedDetails - inner class used as return type from getDemographicsServed
    public class DemographicsServedDetails {
        @AuraEnabled
        List<Demographic_Served__c> demographicServedList {get;set;}
        @AuraEnabled
        Integer numFamiliesServed {get;set;}
    }

    @AuraEnabled
    public static List<String> createGearOrderDemographics(String orderID, Integer totalNumFamiliesServed, String demographicList) {
       	System.debug('GearOrderController > createGearOrderDemographics - orderID: ' + orderID + ', totalNumFamiliesServed: ' + Double.valueOf(totalNumFamiliesServed) + ', demographicList: ' + demographicList);
       	
        // update Gear Order num families served and bulk demographics flag
        Gear_Order__c order = new Gear_Order__c(Id=orderID);
       	order.Num_Families_Served__c = Double.valueOf(totalNumFamiliesServed);
        order.Bulk_Demographics__c = true;
        update order;
        
        // deserialize demographicList json
        List<Object> oList = (List<Object>)JSON.deserializeUntyped(demographicList);
        List<Gear_Order_Demographic__c> orderDemographicList = new List<Gear_Order_Demographic__c>();
        
        System.debug('GearOrderController > createGearOrderDemographics - demographicList: ' + oList + ', list size: ' + oList.size());
        
        for (Integer i = 0; i < oList.size(); ++i) {
            
            Object o = oList.get(i);
            //System.debug('GearOrderController > createGearOrderDemographics - demographic: ' + o);
            
            Map<String, Object> m = (Map<String, Object>) o;
            
            String raceEthnicity = (String) m.get('RaceEthnicity');
        	Integer percentFamiliesServed = Integer.valueOf(m.get('PercentFamiliesServed'));
        	Integer numFamiliesServed = Integer.valueOf(m.get('NumFamiliesServed'));
            
            if (percentFamiliesServed > 0) {
            	// create a set of Gear_Order_Demographic records for the number of families served (NumFamiliesServed) for each RaceEthnicity
            	System.debug('GearOrderController > createGearOrderDemographics - for RaceEthnicity: ' + raceEthnicity + ', creating this number of Gear_Order_Demographic: ' + numFamiliesServed);                        
        	
				for (Integer j = 0; j < numFamiliesServed; ++j) {
                
                    // gear order demographic
                    Gear_Order_Demographic__c orderDemographic = new Gear_Order_Demographic__c();
                    orderDemographic.Gear_Order__c = orderID;
                    orderDemographic.Child_Race_Ethnicity__c = raceEthnicity;
                    orderDemographicList.add(orderDemographic);
                    
                } // end for numFamiliesServed
                
            } // end if percentFamiliesServed > 0
            
        } // for oList
        
        //System.debug('GearOrderController > createGearOrderDemographics - orderDemographicList: ' + orderDemographicList);
        insert orderDemographicList;
        
        List<String> responseList = new List<String>();
        responseList.add('success');
        return responseList;
    } // end getGearOrder

    
} // GearOrderController