force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Custom Product object for donation items</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Available_To_Order__c.field-meta.xml
<CustomField>
    <fullName>Available_To_Order__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>This product can be ordered. Uncheck to make it unavailable to the partner order form.</inlineHelpText>
    <label>Available To Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <description>same as Product Family on standard Product</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donation_Item_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Item_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Item_Bundle__c</fullName>
    <defaultValue>1</defaultValue>
    <description># of items bundled together for fulfilling orders of this product</description>
    <inlineHelpText># of items bundled together for fulfilling orders of this product</inlineHelpText>
    <label>Items In Bundle</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Donation_Item_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Gear</fullName>
    </customValue>
    <customValue>
        <fullName>Activity</fullName>
    </customValue>
    <customValue>
        <fullName>Feeding</fullName>
    </customValue>
    <customValue>
        <fullName>Nursery</fullName>
    </customValue>
    <customValue>
        <fullName>Health &amp; Safety</fullName>
    </customValue>
    <customValue>
        <fullName>Toys</fullName>
    </customValue>
    <customValue>
        <fullName>Books</fullName>
    </customValue>
    <customValue>
        <fullName>Videos &amp; Music</fullName>
    </customValue>
    <customValue>
        <fullName>Clothing</fullName>
    </customValue>
    <customValue>
        <fullName>Bath &amp; Potty</fullName>
    </customValue>
    <description>Donation Item Category</description>
    <masterLabel>Donation Item Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductController.cls
public with sharing class ProductController {
    
    @AuraEnabled
    public static List<Product__c> getProducts() {

        System.debug('ProductController - getProducts');

        InvMgmtCache cache = new InvMgmtCache();
        List<Product__c> productList = cache.getProducts();

        if (productList == null) { // not in cache

            // query Products__c
            productList = [SELECT Id, Name, Family__c, Item_Bundle__c FROM Product__c WHERE Available_To_Order__c = true ORDER BY Family__c ASC, Name ASC];

            // store in cache
            cache.putProducts(productList);
        }

        return productList;

    } // end getProducts
    
} // end ProductController