force-app/main/default/objects/Gear_Order__c/Gear_Order__c.object-meta.xml
<CustomObject>
    <description>Orders for baby gear</description>
    <label>Gear Order</label>
    <nameField>
        <displayFormat>GO-{000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gear Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gear_Order__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>Comments / special requests regarding this order.</description>
    <inlineHelpText>Comments / special requests regarding this order.</inlineHelpText>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Demographic__c/Gear_Order_Demographic__c.object-meta.xml
<CustomObject>
    <label>Gear Order Demographic</label>
    <nameField>
        <displayFormat>GOD-{0000000000}</displayFormat>
        <label>Demographic Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gear Order Demographics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gear_Order_Demographic__c/fields/Child_Age__c.field-meta.xml
<CustomField>
    <fullName>Child_Age__c</fullName>
    <label>Child Age</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Child_Ages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Demographic__c/fields/Child_Gender__c.field-meta.xml
<CustomField>
    <fullName>Child_Gender__c</fullName>
    <label>Child Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Gender_Demographic</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Demographic__c/fields/Child_Race_Ethnicity__c.field-meta.xml
<CustomField>
    <fullName>Child_Race_Ethnicity__c</fullName>
    <label>Child Race/Ethnicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Race_Ethnicity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Demographic__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>Comments / special requests regarding this child.</description>
    <inlineHelpText>Comments / special requests regarding this child.</inlineHelpText>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Demographic__c/fields/Gear_Order__c.field-meta.xml
<CustomField>
    <fullName>Gear_Order__c</fullName>
    <label>Gear Order</label>
    <referenceTo>Gear_Order__c</referenceTo>
    <relationshipLabel>Gear Order Demographics</relationshipLabel>
    <relationshipName>Gear_Order_Demographics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/Gear_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Gear Order Item</label>
    <nameField>
        <displayFormat>GOI-{0000000000}</displayFormat>
        <label>Order Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gear Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gear_Order_Item__c/fields/Clothing_Size__c.field-meta.xml
<CustomField>
    <fullName>Clothing_Size__c</fullName>
    <label>Clothing Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Clothing_Sizes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>Comments / special requests regarding this order item.</description>
    <inlineHelpText>Comments / special requests regarding this order item.</inlineHelpText>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Diaper_Size__c.field-meta.xml
<CustomField>
    <fullName>Diaper_Size__c</fullName>
    <label>Diaper Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Diaper_Sizes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Diaper_Swim_Size__c.field-meta.xml
<CustomField>
    <fullName>Diaper_Swim_Size__c</fullName>
    <label>Diaper (Swim) Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Diaper_Swim_Size</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Gear_Order__c.field-meta.xml
<CustomField>
    <fullName>Gear_Order__c</fullName>
    <label>Gear Order</label>
    <referenceTo>Gear_Order__c</referenceTo>
    <relationshipLabel>Gear Order Items</relationshipLabel>
    <relationshipName>Gear_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Gear_Order_Demographic__c.field-meta.xml
<CustomField>
    <fullName>Gear_Order_Demographic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gear Order Demographic</label>
    <referenceTo>Gear_Order_Demographic__c</referenceTo>
    <relationshipLabel>Gear Order Items</relationshipLabel>
    <relationshipName>Gear_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Gear Order Items</relationshipLabel>
    <relationshipName>Gear_Order_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The number of item bundles of this product.</description>
    <inlineHelpText>The number of item bundles of this product.</inlineHelpText>
    <label>Quantity (Bundles)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Clothing_Seasons</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Custom Product object for donation items</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <description>same as Product Family on standard Product</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donation_Item_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of items of this product in inventory now. This field is calculated.</description>
    <inlineHelpText>The number of items of this product in inventory now. This field is calculated.</inlineHelpText>
    <label># In Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Child_Ages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unknown</fullName>
        <default>true</default>
        <label>Unknown</label>
    </customValue>
    <customValue>
        <fullName>0-3 months</fullName>
    </customValue>
    <customValue>
        <fullName>3-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6-12 months</fullName>
    </customValue>
    <customValue>
        <fullName>12-18 months</fullName>
    </customValue>
    <customValue>
        <fullName>18-24 months</fullName>
    </customValue>
    <customValue>
        <fullName>2-3 years</fullName>
    </customValue>
    <customValue>
        <fullName>3-4 years</fullName>
    </customValue>
    <customValue>
        <fullName>4-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>5-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>10+ years</fullName>
    </customValue>
    <masterLabel>Child Ages</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Clothing_Seasons.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Summer</fullName>
    </customValue>
    <customValue>
        <fullName>Winter</fullName>
    </customValue>
    <masterLabel>Clothing Seasons</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Clothing_Sizes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>N/A</fullName>
        <default>true</default>
        <label>N/A</label>
    </customValue>
    <customValue>
        <fullName>0-3 months</fullName>
    </customValue>
    <customValue>
        <fullName>3-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6-12 months</fullName>
    </customValue>
    <customValue>
        <fullName>12-18 months</fullName>
    </customValue>
    <customValue>
        <fullName>18-24 months</fullName>
    </customValue>
    <customValue>
        <fullName>2T</fullName>
    </customValue>
    <customValue>
        <fullName>3T</fullName>
    </customValue>
    <masterLabel>Clothing Sizes</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Diaper_Sizes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Newborn (Up to 8 lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 1 (8-14lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 2 (12-18lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 3 (16-28lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 4 (22-37bs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 5 (27+lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Size 6 (35+lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Pull Ups (2T-3T)</fullName>
    </customValue>
    <customValue>
        <fullName>Pull Ups (3T-4T)</fullName>
    </customValue>
    <customValue>
        <fullName>Pull Ups (4T-5T)</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Diapers (Small 16-26lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Diapers (Medium 24-34 lbs)</fullName>
    </customValue>
    <customValue>
        <fullName>Swim Diapers (Large 32+ lbs)</fullName>
    </customValue>
    <masterLabel>Diaper Sizes</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Diaper_Swim_Size.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Small 16-26#</fullName>
    </customValue>
    <customValue>
        <fullName>Medium 24-34#</fullName>
    </customValue>
    <customValue>
        <fullName>Large 32 lbs +</fullName>
    </customValue>
    <customValue>
        <fullName>pull-ups 2T-3T</fullName>
        <isActive>false</isActive>
        <label>pull-ups 2T-3T</label>
    </customValue>
    <customValue>
        <fullName>pull-ups 3T-4T</fullName>
        <isActive>false</isActive>
        <label>pull-ups 3T-4T</label>
    </customValue>
    <customValue>
        <fullName>pull-ups 4T-5T</fullName>
        <isActive>false</isActive>
        <label>pull-ups 4T-5T</label>
    </customValue>
    <masterLabel>Diaper (Swim) Size</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Donation_Item_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Gear</fullName>
    </customValue>
    <customValue>
        <fullName>Activity</fullName>
    </customValue>
    <customValue>
        <fullName>Feeding</fullName>
    </customValue>
    <customValue>
        <fullName>Nursery</fullName>
    </customValue>
    <customValue>
        <fullName>Health &amp; Safety</fullName>
    </customValue>
    <customValue>
        <fullName>Toys</fullName>
    </customValue>
    <customValue>
        <fullName>Books</fullName>
    </customValue>
    <customValue>
        <fullName>Videos &amp; Music</fullName>
    </customValue>
    <customValue>
        <fullName>Clothing</fullName>
    </customValue>
    <customValue>
        <fullName>Bath &amp; Potty</fullName>
    </customValue>
    <description>Donation Item Category</description>
    <masterLabel>Donation Item Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Gender_Demographic.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unknown</fullName>
        <default>true</default>
        <label>Unknown</label>
    </customValue>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <masterLabel>Gender Demographic</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Race_Ethnicity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Caucasian</fullName>
    </customValue>
    <customValue>
        <fullName>Native American</fullName>
    </customValue>
    <customValue>
        <fullName>African American</fullName>
    </customValue>
    <customValue>
        <fullName>Hispanic</fullName>
    </customValue>
    <customValue>
        <fullName>Asian</fullName>
    </customValue>
    <customValue>
        <fullName>African</fullName>
    </customValue>
    <customValue>
        <fullName>Other/Unknown</fullName>
        <default>true</default>
        <label>Other/Unknown</label>
    </customValue>
    <masterLabel>Race/Ethnicity</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GearOrder_EmailTemplate_Controller.cls
public class GearOrder_EmailTemplate_Controller {

    public Gear_Order__c order { get; set; }
    
    /** getOrderSummarizedByProduct
     * returns list for populating summary table of products ordered for this gear order
     * list item (ProductSummary): product category, product name, quantity, list of demographics, list of comments
     * quantity = total number (sum) of this product ordered for this gear order
     * list of demographics and list of comments are lined up together. meaning, each comments[i] is for the child represented in demographics[i]
     */
	public List<ProductSummary> getOrderSummarizedByProduct() {
        
        /*
        // unit test
        if (order == null) {
            order = new Gear_Order__c(ID='a021I00000B6sd4QAB');
        }
		*/
        
        String orderID = order.Id;
        System.debug('GearOrder_EmailTemplate_Controller > getOrderSummarizedByProduct - orderID: ' + orderID);
                
        List<Gear_Order_Item__c> orderItemList = 
            [SELECT Id, Name, Gear_Order_Demographic__c, Product__r.Id, Product__r.Name, Product__r.Family__c, Quantity__c, Season__c, Clothing_Size__c, Diaper_Size__c, Diaper_Swim_Size__c, Comment__c 
             FROM Gear_Order_Item__c WHERE Gear_Order__c = :order.Id ORDER BY Product__r.Family__c ASC];
            
        Map<String, ProductSummary> productMap = new Map<String, ProductSummary>();
        Map<ID, Gear_Order_Demographic__c> demographicsMap = getOrderDemographicsMap(orderID);
            
        // create map of product summaries
        for (Integer i = 0; i < orderItemList.size(); ++i) {
            
            Gear_Order_Item__c orderItem = orderItemList.get(i);
            String productName = orderItem.Product__r.Name;
        
            //System.debug('GearOrder_EmailTemplate_Controller > getOrderSummarizedByProduct - (orderItem ' + i + ') productName: ' + productName);
            
            ProductSummary productMapEntry = productMap.get(productName);
            if (productMapEntry == null) {
                
                // create map entry
                productMapEntry = new ProductSummary();
        		productMapEntry.productCategory = orderItem.Product__r.Family__c;
        		productMapEntry.productName = productName;
        		productMapEntry.quantity = orderItem.Quantity__c;
                
                // orderItemDetails
                productMapEntry.orderItemDetails = new List<ProductSummary.OrderItemDetail>();
                ProductSummary.OrderItemDetail orderItemDetail = new ProductSummary.OrderItemDetail();
				orderItemDetail.demographic = demographicsMap.get(orderItem.Gear_Order_Demographic__c);
				orderItemDetail.orderItem = orderItem;
				productMapEntry.orderItemDetails.add(orderItemDetail);
                
                // add to map
                productMap.put(productName, productMapEntry);
                
            } else { // update map entry
                
                // quantity sum
                productMapEntry.quantity += orderItem.Quantity__c;
                
                // orderItemDetails
                ProductSummary.OrderItemDetail orderItemDetail = new ProductSummary.OrderItemDetail();
				orderItemDetail.demographic = demographicsMap.get(orderItem.Gear_Order_Demographic__c);
				orderItemDetail.orderItem = orderItem;              
                productMapEntry.orderItemDetails.add(orderItemDetail);    
                
            }
            
        } // end for order items
        
        // productSummaryList - from productMap
        List<ProductSummary> productSummaryList = new List<ProductSummary>();
        
        for (String productName : productMap.keySet()) {
			productSummaryList.add(productMap.get(productName));
		}
        
        return productSummaryList;
        
    } // end getOrderSummarizedByProduct
    
    private Map<ID, Gear_Order_Demographic__c> getOrderDemographicsMap(String orderID) {
                
        List<Gear_Order_Demographic__c> demographicsList =
            [SELECT Child_Age__c, Child_Gender__c, Child_Race_Ethnicity__c, Comment__c FROM Gear_Order_Demographic__c WHERE Gear_Order__c = :orderID];  
		
        Map<ID, Gear_Order_Demographic__c> demographicsMap = new Map<ID, Gear_Order_Demographic__c>();   
        
		// create map of demographics
        for (Integer i = 0; i < demographicsList.size(); ++i) {             
            Gear_Order_Demographic__c demographic = demographicsList.get(i);            
            demographicsMap.put(demographic.Id, demographic);            
        }
            
        return demographicsMap;
        
    } // end getDemographicsMap 
    
} // end GearOrder_EmailTemplate_Controller