force-app/main/default/objects/Gear_Order__c/Gear_Order__c.object-meta.xml
<CustomObject>
    <description>Orders for baby gear</description>
    <label>Gear Order</label>
    <nameField>
        <displayFormat>GO-{000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gear Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gear_Order_Item__c/Gear_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Gear Order Item</label>
    <nameField>
        <displayFormat>GOI-{0000000000}</displayFormat>
        <label>Order Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gear Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gear_Order_Item__c/fields/Fulfilled__c.field-meta.xml
<CustomField>
    <fullName>Fulfilled__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Uncheck if this line item couldn&#39;t be fulfilled, or not fulfilled with the requested quantity</inlineHelpText>
    <label>Fulfilled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Gear_Order__c.field-meta.xml
<CustomField>
    <fullName>Gear_Order__c</fullName>
    <label>Gear Order</label>
    <referenceTo>Gear_Order__c</referenceTo>
    <relationshipLabel>Gear Order Items</relationshipLabel>
    <relationshipName>Gear_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Gear Order Items</relationshipLabel>
    <relationshipName>Gear_Order_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The number of item bundles of this product.</description>
    <inlineHelpText>The number of item bundles of this product.</inlineHelpText>
    <label>Quantity (Bundles)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Quantity_Fulfilled__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Fulfilled__c</fullName>
    <label>Quantity (Bundles) Fulfilled</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Custom Product object for donation items</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Item_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Item_Bundle__c</fullName>
    <defaultValue>1</defaultValue>
    <description># of items bundled together for fulfilling orders of this product</description>
    <inlineHelpText># of items bundled together for fulfilling orders of this product</inlineHelpText>
    <label>Items In Bundle</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of items of this product in inventory now. This field is calculated.</description>
    <inlineHelpText>The number of items of this product in inventory now. This field is calculated.</inlineHelpText>
    <label># In Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Quantity_Needed__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Needed__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of items of this product that are needed to fulfill pending orders. This field is calculated.</description>
    <inlineHelpText>The number of items of this product that are needed to fulfill pending orders. This field is calculated.</inlineHelpText>
    <label># Needed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProcessInventory_GearOrderUnfulfilled.cls
global without sharing class ProcessInventory_GearOrderUnfulfilled {

    @InvocableMethod(label='Unfulfill Gear Order')    
    global static void unfulfillGearOrderItems(List<Gear_Order__c> orders) {
		
        if (orders != null) {

       		// orderIds
            List<Id> orderIds = new List<Id>();
            for(Gear_Order__c order : orders) { orderIds.add(order.Id); }
            
            // order map w/ list of order line items
            Map<Id, Gear_Order__c> orderMap = new Map<Id, Gear_Order__c>(
            	[SELECT Id, (SELECT Id, Name, Product__c, Quantity__c, Quantity_Fulfilled__c, Fulfilled__c FROM Gear_Order_Items__r) FROM Gear_Order__c WHERE Id IN :orderIds]);
            
            // product map
            Map<Id, Product__c> productMap = new Map<Id, Product__c>(
            	[SELECT Id, Name, Item_Bundle__c, Quantity__c, Quantity_Needed__c FROM Product__c]);          
            
            // products to update map (using map because it's possible to have multiple lines items for the same product but different gender)
           	Map<Id, Product__c> productsToUpdateMap = new Map<Id, Product__c>();
            
            // line items to update list
            List<Gear_Order_Item__c> orderItemsToUpdateList = new List<Gear_Order_Item__c>();
            
            for(Gear_Order__c order : orders) {
                System.debug('ProcessInventory_GearOrderFulfilled - order: ' + order.Id);
                
                // get order line items as children of the order
                List<Gear_Order_Item__c> lineItems = orderMap.get(order.Id).Gear_Order_Items__r;                
                System.debug('ProcessInventory_GearOrderUnfulfilled - lineItems empty: ' + lineItems.isEmpty());
                
                if (!lineItems.isEmpty()) {
                
                    for(Gear_Order_Item__c lineItem : lineItems) {                    
                        System.debug('ProcessInventory_GearOrderUnfulfilled - lineItem: ' + lineItem);
                    
                        // get product for this line item. use product in productsToUpdateMap if it exists
                        Product__c product = null;
                        if (productsToUpdateMap.containsKey(lineItem.Product__c)) {
                            product = productsToUpdateMap.get(lineItem.Product__c);
                        } else {
                            product = productMap.get(lineItem.Product__c);
                        }       
                        if (product.Item_Bundle__c == null) { product.Item_Bundle__c = 1; }
                        System.debug('ProcessInventory_GearOrderUnfulfilled - lineItem product: ' + product);                         
                        
                        // set line item to 'unfulfilled'
                        lineItem.Fulfilled__c = false;
                        orderItemsToUpdateList.add(lineItem);
                        
                        // update product quantity needed - subtract the full quantity for this line item
                        product.Quantity_Needed__c = product.Quantity_Needed__c - (lineItem.Quantity__c * product.Item_Bundle__c);
                        if (product.Quantity_Needed__c < 0) { product.Quantity_Needed__c = 0; }
                        
                        System.debug('ProcessInventory_GearOrderUnfulfilled - new product quantities: ' + product);
                        productsToUpdateMap.put(product.Id, product);
                        
                    } // end for line items
                    
                } // end if line items
                
            } // end for orders
            
            // update order line items
            update orderItemsToUpdateList;
            System.debug('ProcessInventory_GearOrderUnfulfilled - gear order line items unfulfilled: ' + orderItemsToUpdateList);
            
            // update product quantities
            List<Product__c> productsToUpdate = productsToUpdateMap.values();
            update productsToUpdate;
            System.debug('ProcessInventory_GearOrderUnfulfilled - product quantities updated: ' + productsToUpdate.size());
            
        } // end if orders
        
    } // end unfulfillGearOrderItems   
    
} // end ProcessInventory_GearOrderUnfulfilled