force-app/main/default/objects/Gear_Order__c/Gear_Order__c.object-meta.xml
<CustomObject>
    <description>Orders for baby gear</description>
    <label>Gear Order</label>
    <nameField>
        <displayFormat>GO-{000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gear Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gear_Order__c/fields/Order_Created__c.field-meta.xml
<CustomField>
    <fullName>Order_Created__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Order Created</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Gear_Order__c/fields/Partner_Organization__c.field-meta.xml
<CustomField>
    <fullName>Partner_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Gear Orders</relationshipLabel>
    <relationshipName>Gear_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Demographic__c/Gear_Order_Demographic__c.object-meta.xml
<CustomObject>
    <label>Gear Order Demographic</label>
    <nameField>
        <displayFormat>GOD-{0000000000}</displayFormat>
        <label>Demographic Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gear Order Demographics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gear_Order_Demographic__c/fields/Gear_Order__c.field-meta.xml
<CustomField>
    <fullName>Gear_Order__c</fullName>
    <label>Gear Order</label>
    <referenceTo>Gear_Order__c</referenceTo>
    <relationshipLabel>Gear Order Demographics</relationshipLabel>
    <relationshipName>Gear_Order_Demographics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/Gear_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Gear Order Item</label>
    <nameField>
        <displayFormat>GOI-{0000000000}</displayFormat>
        <label>Order Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gear Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gear_Order_Item__c/fields/Gear_Order__c.field-meta.xml
<CustomField>
    <fullName>Gear_Order__c</fullName>
    <label>Gear Order</label>
    <referenceTo>Gear_Order__c</referenceTo>
    <relationshipLabel>Gear Order Items</relationshipLabel>
    <relationshipName>Gear_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Gear_Order_Demographic__c.field-meta.xml
<CustomField>
    <fullName>Gear_Order_Demographic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gear Order Demographic</label>
    <referenceTo>Gear_Order_Demographic__c</referenceTo>
    <relationshipLabel>Gear Order Items</relationshipLabel>
    <relationshipName>Gear_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Gear Order Items</relationshipLabel>
    <relationshipName>Gear_Order_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Order line item value = Quantity Fulfilled x Product Value</description>
    <label>Value</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Item__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <inlineHelpText>The weight (lbs) of the items in this order line item. This field is calculated as quantity times product weight (lbs).</inlineHelpText>
    <label>Weight (lbs)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Custom Product object for donation items</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <description>same as Product Family on standard Product</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donation_Item_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>$ value of this item</description>
    <inlineHelpText>$ value of this item</inlineHelpText>
    <label>Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>The weight of this product in the selected Weight Unit of Measure (Examples: 1 pound, 64 kilograms, 12 ounces)</description>
    <inlineHelpText>The weight of this product in the selected Weight Unit of Measure (Examples: 1 pound, 64 kilograms, 12 ounces)</inlineHelpText>
    <label>Weight</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Donation_Item_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Gear</fullName>
    </customValue>
    <customValue>
        <fullName>Activity</fullName>
    </customValue>
    <customValue>
        <fullName>Feeding</fullName>
    </customValue>
    <customValue>
        <fullName>Nursery</fullName>
    </customValue>
    <customValue>
        <fullName>Health &amp; Safety</fullName>
    </customValue>
    <customValue>
        <fullName>Toys</fullName>
    </customValue>
    <customValue>
        <fullName>Books</fullName>
    </customValue>
    <customValue>
        <fullName>Videos &amp; Music</fullName>
    </customValue>
    <customValue>
        <fullName>Clothing</fullName>
    </customValue>
    <customValue>
        <fullName>Bath &amp; Potty</fullName>
    </customValue>
    <description>Donation Item Category</description>
    <masterLabel>Donation Item Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GearOrder_EmailTemplate_Controller_Test.cls
@isTest
public class GearOrder_EmailTemplate_Controller_Test {

    @isTest static void test_getOrderSummarizedByProduct() {
        
        System.debug('GearOrder_EmailTemplate_Controller_Test >> test_getOrderSummarizedByProduct > start');
        
        // partner organization
        Account partnerOrg = new Account(Name='Test Partner Organization');
        insert partnerOrg;
        
        // order
        Gear_Order__c order = new Gear_Order__c(Partner_Organization__c=partnerOrg.Id,
                                               Order_Created__c=dateTime.now());
        insert order;
        String orderID = order.Id;
        
        // product
        Product__c product = new Product__c(Family__c='None', Name='TestProduct1', Value__c=1,Weight__c=1); 
        insert product;
        
        // gear order demographics
        Integer childNum = 0;
        String childAlias = 'Child ' + (++childNum);
        String childGender = 'Unknown';
        String childAge = 'Unknown';
        String childRaceEthnicity = 'Other/Unknown';
        String parentGender = 'Unknown';
        String parentAge = 'Unknown';
        String parentRaceEthnicity = 'Other/Unknown';
        String parentMaritalStatus = 'Unknown';
        String demographicComment = 'test comment';
        
        Gear_Order_Demographic__c demographic = GearOrderDemographicsController.createGearOrderDemographic(orderID, childAlias, 
            childGender, childAge, childRaceEthnicity,parentGender, parentAge, parentRaceEthnicity, parentMaritalStatus, 
            demographicComment);

		// order items        	 
        
        // orderItem 1 - product 1
        String demographicID = demographic.Id;
        String productID = product.Id;
        Integer quantity = 1;
        String comment = 'test comment 1';
        Gear_Order_Item__c orderItem1 = GearOrderController.createGearOrderItem(orderID, demographicID, productID, quantity, null, null, null, comment);               
        
        // orderItem 2 - product 1
        demographicID = null;
        productID = product.Id;
        quantity = 1;
        comment = 'test comment 2';
        Gear_Order_Item__c orderItem2 = GearOrderController.createGearOrderItem(orderID, demographicID, productID, quantity, null, null, null, comment);               
        
        // getOrderSummarizedByProduct
        GearOrder_EmailTemplate_Controller controller = new GearOrder_EmailTemplate_Controller();
        controller.order = order;
        List<ProductSummary> productSummaryList = controller.getOrderSummarizedByProduct();
        System.debug('GearOrder_EmailTemplate_Controller_Test > test_getOrderSummarizedByProduct: ' + productSummaryList);

        // test ProductSummary get methods
        for (Integer i = 0; i < productSummaryList.size(); ++i) {
            ProductSummary summary = productSummaryList.get(0);
            System.debug('productSummary ' + i + ' - Category: ' + summary.productCategory + ', Product: ' + summary.productName + ', Quantity: ' + summary.quantity);  
			List<ProductSummary.OrderItemDetail> orderItemDetails = summary.orderItemDetails;
            for (Integer j = 0; j < orderItemDetails.size(); ++j) {
                ProductSummary.OrderItemDetail orderItemDetail = orderItemDetails.get(0);
                System.debug('\t orderItemDetail ' + j + ' - Demographic: ' + orderItemDetail.demographicDisplay + ', Details: ' + orderItemDetail.orderItemDisplay + ', Comments: ' + orderItemDetail.commentsDisplay);
            }
        }
        
    } // end test_getOrderSummarizedByProduct 
    
} // end GearOrder_EmailTemplate_Controller_Test